=== chitamango/acc-system/src/AccSchema.xsd
<?xml version = "1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swin.edu.au" xmlns="http://www.swin.edu.au" elementFormDefault="qualified">
<xsd:element name="coordination">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="roles" type="rolesType" minOccurs = "1" maxOccurs = "1" />
	  <xsd:element name="shared_artifacts" type="sharedArtifactsType" minOccurs = "1" maxOccurs = "1" />
      <xsd:element name="shared_rules" type="sharedRulesType" minOccurs = "1" maxOccurs = "1" />   
    </xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
</xsd:element>


<xsd:complexType name="rolesType">
  <xsd:sequence>
    <xsd:element name="role" type="roleType" minOccurs = "1" maxOccurs = "unbounded" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="sharedArtifactsType">
  <xsd:sequence>
    <xsd:element name="shared_artifact" type="sharedArtifactType" minOccurs = "1" maxOccurs = "unbounded" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="sharedRulesType">
  <xsd:sequence>
    <xsd:element name="shared_rule" type="sharedRuleType" minOccurs = "1" maxOccurs = "unbounded" />
  </xsd:sequence>
 <!-- <xsd:attribute name="rulefile" type="xsd:string" use="required"/> -->
</xsd:complexType>



<xsd:complexType name="roleType"> 
	<xsd:sequence>
    <xsd:element name="service" type="serviceType" minOccurs = "1" maxOccurs = "unbounded" />
  </xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required" />
	<xsd:attribute name="namespace" type="xsd:string" use="required" />
	<xsd:attribute name= "role_location" type="xsd:string" use="required" />
	<xsd:attribute name= "role_port" type="xsd:string" use="required" />
</xsd:complexType>

<xsd:complexType name="sharedArtifactType"> 
	 <xsd:sequence>
		<xsd:element name="attributes" type="attributesType" minOccurs = "1" maxOccurs = "1" />
		<xsd:element name="shared_states" type="sharedStatesType" minOccurs = "1" maxOccurs = "1" />
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required" />
</xsd:complexType>



<xsd:complexType name="sharedRuleType"> 
	 <xsd:sequence>
		<xsd:element name="onEvent" type="onEventType" maxOccurs = "1" minOccurs = "1" />
		<xsd:element name="preCon" type="preconType" maxOccurs = "1" minOccurs = "1" />
		<xsd:element name="do" type="doType" maxOccurs = "1" minOccurs = "1" />
		<xsd:element name="postCon" type="postconType" maxOccurs = "1" minOccurs = "1" />
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="serviceType"> 
    <xsd:attribute name="name" type="xsd:string" use="required" />
	<xsd:attribute name="inputmessage" type="xsd:string" use="required" />
	<xsd:attribute name="outputmessage" type="xsd:string" use="required" />
	<xsd:attribute name="operation" type="xsd:string" use="required" />
	<xsd:attribute name="port" type="xsd:string" use="required"/>
	<xsd:attribute name="location" type="xsd:anyURI" use="required"/> 
</xsd:complexType>

<xsd:complexType name="attributesType"> 
	 <xsd:sequence>
		<xsd:element name="attribute" minOccurs = "1" maxOccurs = "unbounded" >
			<xsd:complexType>
				<xsd:attribute name="name" type="xsd:string" use="required"/>
				<xsd:attribute name="structure"  use="required"> <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							  <xsd:enumeration value="pair"/>
							  <xsd:enumeration value="list"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="type"  use="required"> <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							  <xsd:enumeration value="string"/>
							  <xsd:enumeration value="integer"/>
							  <xsd:enumeration value="short" />
							  <xsd:enumeration value="long"/>
							  <xsd:enumeration value="double"/>
							  <xsd:enumeration value="artifact"/>
							  <xsd:enumeration value="boolean"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="unique_id"  use="optional"> <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							  <xsd:enumeration value="yes"/>
							  <xsd:enumeration value="no"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:complexType>
		</xsd:element>
	</xsd:sequence>  
</xsd:complexType>

<xsd:complexType name="sharedStatesType"> 
	 <xsd:sequence>
		<xsd:element name="state" minOccurs = "2" maxOccurs = "unbounded" >
			<xsd:complexType>
				<xsd:attribute name="name"  use="required"/>
				<xsd:attribute name="type" > <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							  <xsd:enumeration value="init"/>
							  <xsd:enumeration value="end"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:complexType>
		</xsd:element>
	</xsd:sequence>  
</xsd:complexType>

<xsd:complexType name="onEventType"> 	
	<xsd:attribute name="type"  use="required">		<!-- restriced value -->
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="messageReceivedEvent"/>
				<xsd:enumeration value="artifactChangedEvent"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>		
</xsd:complexType>

<xsd:complexType name="preconType"> 
	 <xsd:sequence>
		<xsd:element name="and" type = "andType" minOccurs = "1" maxOccurs = "1" />	
	</xsd:sequence>  
</xsd:complexType>

<xsd:complexType name="postconType"> 
	 <xsd:sequence>
		<xsd:element name="and" type = "andType" minOccurs = "1" maxOccurs = "1" />	
	</xsd:sequence>  
</xsd:complexType>


<xsd:complexType name="andType"> 
	 <xsd:sequence>
		<xsd:element name="atom" minOccurs = "1" maxOccurs = "unbounded"  >	
			<xsd:complexType> 
				<xsd:attribute name="artifact" type="xsd:string" use="optional"/>
				<xsd:attribute name="id" type="xsd:string" use="optional"/>
				<xsd:attribute name="attribute" type="xsd:string" use="optional"/>
				<xsd:attribute name="value" type="xsd:string" use="required"/>
				<xsd:attribute name="type"  use="required"> <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="attribute"/>
							<xsd:enumeration value="state"/>
							<xsd:enumeration value="input"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="op"  use="optional"> <!-- restriced value -->
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="=="/>
							<xsd:enumeration value="&gt;"/>
							<xsd:enumeration value="&lt;" />
							<xsd:enumeration value="&lt;=" />
							<xsd:enumeration value="&gt;=" />
							<xsd:enumeration value="!=" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:complexType> 	
		</xsd:element>
	</xsd:sequence>  
</xsd:complexType>

<xsd:complexType name="doType"> 
	 <xsd:sequence>
		<xsd:element name="invoke" type="invokeType"  maxOccurs = "1" minOccurs = "1" />
	</xsd:sequence> 
</xsd:complexType>

<xsd:complexType name="invokeType"> 
	 <xsd:sequence>
		<xsd:element name="mapping" type="mappingType"  maxOccurs = "1" minOccurs = "1" />
		<xsd:element name="transitions" type = "transitionsType" maxOccurs = "1" minOccurs = "1"  />
	</xsd:sequence>
	<xsd:attribute name="role" type="xsd:string" use="required"/>
	<xsd:attribute name="service" type="xsd:string" use="required"/>
	<xsd:attribute name="operation" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="mappingType"> 
	 <xsd:sequence>
	 	<xsd:element name="coordination" type = "coordinationType" minOccurs = "1" maxOccurs = "1" />
		<xsd:element name="notification" type = "notificationType" minOccurs = "1" maxOccurs = "1" />
	</xsd:sequence> 
</xsd:complexType>

<xsd:complexType name="transitionsType">
	<xsd:sequence>	
			<xsd:element name="transition"  type = "transitionType"  minOccurs = "0" maxOccurs = "unbounded" />
	</xsd:sequence>	
</xsd:complexType>

<xsd:complexType name="coordinationType">
	<xsd:sequence>	
		<xsd:element name="map" type = "maptype"  minOccurs = "0" maxOccurs = "unbounded" />	
	</xsd:sequence>	
</xsd:complexType>

<xsd:complexType name="notificationType">
	<xsd:sequence>	
		<xsd:element name="map" type = "maptype"  minOccurs = "0" maxOccurs = "unbounded" />	
	</xsd:sequence>	
</xsd:complexType>

<xsd:complexType name="maptype">
	<xsd:all>
		<xsd:element name= "from" type = "fromType" />
		<xsd:element name= "to" type = "toType" />	
	</xsd:all>
</xsd:complexType>


<xsd:complexType name = "fromType">
	<xsd:attribute name="type" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="message"/>
				<xsd:enumeration value="local_artifact"/>
				<xsd:enumeration value="shared_artifact"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="part" type="xsd:string" use="optional"/>
	<xsd:attribute name="attribute" type="xsd:string" use="optional"/>	
</xsd:complexType>

<xsd:complexType name = "toType">
	<xsd:attribute name="type" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="message"/>
				<xsd:enumeration value="local_artifact"/>
				<xsd:enumeration value="shared_artifact"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="part" type="xsd:string" use="optional"/>
	<xsd:attribute name="attribute" type="xsd:string" use="optional"/>	
</xsd:complexType>


<xsd:complexType name="transitionType">
	<xsd:attribute name="shared_artifact" type="xsd:string" use="required"/> 
	<xsd:attribute name="fromState" type="xsd:string" use="required"/>
	<xsd:attribute name="toState" type="xsd:string" use="required"/>
</xsd:complexType>

</xsd:schema>

=== chitamango/acc-system/definition/purchase-process.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version 1.1 -->
<coordination xmlns="http://www.swin.edu.au" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.swin.edu.au AccSchema.xsd" name = "purchase-process">
	<shared_artifacts>
		<shared_artifact name = "purchase_order" >
			<attributes>
				<attribute name = "orderId" type ="string" structure = "pair" unique_id = "yes" />
				<attribute name = "supplierId" type ="string" structure = "pair"/>
				<attribute name = "summittedDate" type ="string" structure = "pair"/>
				<attribute name = "confirmedDate" type ="string" structure = "pair"/>
				<attribute name = "cancelledDate" type ="string" structure = "pair"/>
				<attribute name = "filledDate" type ="string" structure = "pair"/>
				<attribute name = "productItem" type ="string" structure = "pair"/>
				<attribute name = "quantity" type ="string" structure = "pair"/>
				<attribute name = "filledQuantity" type ="string" structure = "pair"/>
				<attribute name = "subTotal" type ="string" structure = "pair"/>
				<attribute name = "tax" type ="string" structure = "pair"/>
				<attribute name = "total" type ="string" structure = "pair"/>
				<attribute name = "current_stock" type ="string" structure = "pair"/>
				<attribute name = "stockcheckingDate" type ="string" structure = "pair"/>
			</attributes>
			<shared_states>
				<state name = "init" type = "init"/>
				<state name = "created" />	
				<state name = "on_hold" />
				<state name = "confirmed" />	
				<state name = "accepted" />
				<state name = "acquiring" />			
				<state name = "filled" />	
				<state name = "ready_to_ship" />
				<state name = "delivery" />
				<state name = "billing" />		
				<state name = "closed" type = "end" />	
				<state name = "cancelled" type = "end" />	
			</shared_states>
		</shared_artifact>
		<shared_artifact name = "shipping_order" >
			<attributes>
				<attribute name = "shippingID" type ="string" structure = "pair" unique_id = "yes" />
				<attribute name = "shipperName" type ="string" structure = "pair"/>
				<attribute name = "scheduledDateTime" type ="string" structure = "pair"/>
				<attribute name = "shippedDateTime" type ="string" structure = "pair"/>
				<attribute name = "arrivedDateTime" type ="string" structure = "pair"/>
				<attribute name = "shippingNote" type ="string" structure = "pair"/>
				<attribute name = "shippingAddress" type ="string" structure = "pair"/>
				<attribute name = "totalWeight" type ="string" structure = "pair"/>
			</attributes>
			<shared_states>
				<state name = "init" type = "init"/>	
				<state name = "created" />
				<state name = "scheduled" />
				<state name = "in_transit" />
				<state name = "arrived" type = "end"/>
			</shared_states>
		</shared_artifact>
		<shared_artifact name = "invoice" >
			<attributes>
				<attribute name = "invoiceID" type ="string" structure = "pair" unique_id = "yes" />
				<attribute name = "invoiceDate" type ="string" structure = "pair"/>
				<attribute name = "term" type ="string" structure = "pair"/>
				<attribute name = "amount" type ="string" structure = "pair"/>
				<attribute name = "currency" type ="string" structure = "pair"/>
				<attribute name = "clearAmount" type ="tring" structure = "pair"/>
				<attribute name = "clearDate" type ="string" structure = "pair"/>
			</attributes>
			<shared_states>
				<state name = "init" type = "init"/>	
				<state name = "issued" />		
				<state name = "sent" />
				<state name = "unpaid" />
				<state name = "clearing" />
				<state name = "on_board_to_destination" type = "end"/>
				<state name = "delivered" type = "end"/>
			</shared_states>
		</shared_artifact>
	
	</shared_artifacts>
	<shared_rules>
		<shared_rule name ="r01-createPOprocess">
			<onevent type = "messageReceivedEvent" />
			<pre_con> 
				<and>			
					<atom type = "part" message = "makePurchaseRequest"  part = "supplierId" operator = "!=" value = "null" />
					<atom type = "part" message = "makePurchaseRequest"  part = "productItem" operator = "!=" value = "null" /> 
					<atom type = "part" message = "makePurchaseRequest"  part = "quantity" operator = "!=" value = "null" /> 
				</and>
			
			</pre_con>
			<do>
				<invoke role = "buyer" service = "BuyerServiceInterface" operation = "createPO" >
					<mapping>
						<coordination>
							<map>
								<from type = "message" name = "makePurchaseRequest" part = "supplierId"  />
								<to type = "message" name = "createPORequest" part = "supplierId" /> 
							</map>
							<map>
								<from type = "message" name = "makePurchaseRequest" part = "productItem"  />
								<to type = "message" name = "createPORequest" part = "productItem" />
							</map>
							<map>
								<from type = "message" name = "makePurchaseRequest" part = "quantity"  />
								<to type = "message" name = "createPORequest" part = "quantity" />
							</map>
						</coordination>
						<notification> 
							<map>
								<from type = "local_artifact" name = "quote" attribute = "quoteId" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "orderId"   />
							</map>
							<map>
								<from type = "local_artifact" name = "quote" attribute = "supplierId" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "supplierId"   />
							</map>
							<map>
								<from type = "local_artifact" name = "quote" attribute = "submittedDate" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "summittedDate"   />
							</map>
							<map>
								<from type = "local_artifact" name = "quote" attribute = "productItem" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "productItem"   />
							</map>
							<map>
								<from type = "local_artifact" name = "quote" attribute = "quantity" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "quantity"   />
							</map>
						</notification> 
					</mapping>
					<transitions>
						<transition shared_artifact = "purchase_order" fromState = "init" toState = "created" />
					</transitions>	
				</invoke>	
			</do>
		</shared_rule>
		<shared_rule name ="r16-waitingforconfirmation">
			<onevent type = "artifactChangedEvent" />
			<pre_con> 
				<and>			
					<atom type = "part" shared_artifact = "purchase_order"  attibute_name = "id" operator = "!=" value = "null" />
					<atom type = "part" shared_artifact = "purchase_order"  attibute_name = "customer" operator = "!=" value = "null" /> 
					<atom type="state" shared_artifact = "purchase_order" value="init"  /> 
				</and>
			
			</pre_con>
			<do>
				<invoke role = "system" service = "selfTransistionService" operation = "stateTransist" >
					<mapping>
						<coordination>
							
						</coordination>
						<notification> 
							
						</notification> 
					</mapping>
					<transitions>
						<transition shared_artifact = "purchase_order" fromState = "created" toState = "on_hold" />
					</transitions>	
				</invoke>	
			</do>
		</shared_rule>
		<shared_rule name ="r2-confirmationPO">
			<onevent type = "messageReceivedEvent" />
			<pre_con> 
				<and>	
					<atom type = "part" message = "makePurchaseRequest"  part = "status" operator = "!=" value = "string:confirm" /> 
					<atom type = "attribute" shared_artifact = "purchase_order"  attibute_name = "summittedDate" operator = "!=" value = "null" /> 
					<atom type="state" shared_artifact = "purchase_order" value="on_hold"  /> 
				</and>
			
			</pre_con>
			<do>
				<invoke role = "buyer" service = "BuyerServiceInterface" operation = "confirmPO" >
					<mapping>
						<coordination>
							<map>
								<from type = "shared_artifact" name = "purchase_order" attribute = "orderId"  />
								<to type = "message" name = "confirmPORequest" part = "quoteId" /> 
							</map>
							<map>
								<from type = "message" name = "makePurchaseRequest" part = "status"  />
								<to type = "message" name = "confirmPORequest" part = "confirm" />
							</map>
							
						</coordination>
						<notification> 
							<map>
								<from type = "local_artifact" name = "quote" attribute = "comfirmedDate" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "confirmedDate"   />
							</map>
						
						</notification> 
					</mapping>
					<transitions>
						<transition shared_artifact = "purchase_order" fromState = "on_hold" toState = "confirmed" />
					</transitions>	
				</invoke>	
			</do>
		</shared_rule>
		<shared_rule name ="r3-cancellationPO">
			<onevent type = "messageReceivedEvent" />
			<pre_con> 
				<and>		
					<atom type = "part" message = "makePurchaseRequest"  part = "status" operator = "!=" value = "string:cancel" /> 
					<atom type = "attribute" shared_artifact = "purchase_order"  attibute_name = "summittedDate" operator = "!=" value = "null" /> 
					<atom type="state" shared_artifact = "purchase_order" value="on_hold"  /> 
				</and>
			
			</pre_con>
			<do>
				<invoke role = "buyer" service = "BuyerServiceInterface" operation = "cancelPO" >
					<mapping>
						<coordination>
							<map>
								<from type = "shared_artifact" name = "purchase_order" attribute = "orderId"  />
								<to type = "message" name = "cancelPORequest" part = "quoteId" /> 
							</map>
							<map>
								<from type = "message" name = "makePurchaseRequest" part = "status"  />
								<to type = "message" name = "cancelPORequest" part = "cancel" />
							</map>
							
						</coordination>
						<notification> 
							<map>
								<from type = "local_artifact" name = "quote" attribute = "cancelledDate" />
								<to type = "shared_artifact" name = "purchase_order" attribute = "cancelledDate"   />
							</map>
						</notification> 
					</mapping>
